# Projection Matrices for lines and planes

This is an exploration of Chapter 6 part 2 of Introduction to Linear Algebra -- Gilbert Strang.

We will look at the theory behind the following topics as well as implmenting some matrix algoritms in python. 

- Projection matrices.
- Projecting onto a line.
- Projection onto a plane

![image](./static/projections.png)

In [1]:
import numpy as np
import plotly
import plotly.graph_objs as go

In [2]:
P_xy = np.matrix([[1, 0, 0], [0, 1, 0], [0, 0, 0]]) 
P_z = np.matrix([[0, 0, 0], [0, 0, 0], [0, 0, 1]])

In [3]:
b = np.matrix([2,3,4])
p_xy = P_xy*b.T
p_z = P_z*b.T

In [4]:
b = b.reshape(-1)[0].tolist()[0]
p_xy = p_xy.reshape(-1)[0].tolist()[0]
p_z =  p_z.reshape(-1)[0].tolist()[0]

In [42]:
vector_plot([b, p_xy, p_z])

In [43]:
def proj_onto_line(vect_a, vect_b):
    
    a1, a2, a3 = vect_a
    b1, b2, b3 = vect_b
    
    vect_a = np.array(vect_a)
    
    vect_b = np.array(vect_b)
    
    P_a = np.outer(vect_a, vect_a) / vect_a.dot(vect_a)
    


    p1, p2, p3 = P_a.dot(vect_b.T)
    
    
    
    
    data = []
    vector = go.Scatter3d(x = [0,a1],
                          y = [0,a2],
                          z = [0,a3],
                          marker = dict(size = [0,5],
                                        color = ['blue'],
                                        line=dict(width=5,
                                        color='DarkSlateGrey')),
                        name = 'a')
                               
    data.append(vector)
    
    vector = go.Scatter3d(x = [0,b1],
                          y = [0,b2],
                          z = [0,b3],
                          marker = dict(size = [0,5],
                                        color = ['blue'],
                                        line=dict(width=5,
                                        color='DarkSlateGrey'
                                                 )),
                        name = 'b')
                               
               
    data.append(vector)
    
    
    vector = go.Scatter3d(x = [0,p1],
                          y = [0,p2],
                          z = [0,p3],
                          marker = dict(size = [0,5],
                                        color = ['blue'],
                                        line=dict(width=5,
                                        color='DarkSlateGrey'
                                                 )),
                        name = 'projection')
    
    data.append(vector)

    
    vector = go.Scatter3d(x = [b1,p1],
                          y = [b2,p2],
                          z = [b3,p3],
                          marker = dict(size = [0,5],
                                        color = ['blue'],
                                        line=dict(width=5,
                                        color='DarkSlateGrey'
                                                 )),
                        name = 'error')
    
    data.append(vector)
    
    layout = go.Layout(
             margin = dict(l = 4,
                           r = 4,
                           b = 4,
                           t = 4)
                  )
    fig = go.Figure(data=data,layout=layout)
    fig.show()
                               
                               

In [44]:
proj_onto_line([1, 2, 2], [1, 1, 1])

## Projecting onto a Plane

In [45]:
A = np.matrix([[1, 0], [1, 1], [1, 2]])
b = np.matrix([6, 0 , 0])

In [46]:
A.T*A

matrix([[3, 3],
        [3, 5]])

In [47]:
A.T.dot(b.T)

matrix([[6],
        [0]])

In [48]:
def calc_proj_matrix(A):
    return A*np.linalg.inv(A.T*A)*A.T

In [49]:
P = calc_proj_matrix(A)

In [50]:
def calc_proj(b, A):
    P = calc_proj_matrix(A)
    return P*b.T

In [51]:
calc_proj(b, A)

matrix([[ 5.],
        [ 2.],
        [-1.]])

In [55]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots



def plot_projection_onto_surface(b, A):
    
    x1, x2, x3 = b
    
    line =  np.matrix(b)

    calc_proj_matrix(A)
    p = calc_proj(line, A)
    
    p1, p2, p3 = np.array(p)
    

    
    v1 = np.array(A.T[0])
    v2 = np.array(A.T[1])
    
    cp = np.cross(v1, v2)

    print(cp)
    a, b, c = cp[0]

    # fix the plane to go through the origin
    d = 0


    x = np.linspace(-2, 14, 5)
    y = np.linspace(-2, 14, 5)
    X, Y = np.meshgrid(x, y)

    Z = (d - a * X - b * Y) / c


    fig = go.Figure(
        data=go.Surface(
        x=X, y=Y, z=Z, colorscale='Greys',name='Eon', opacity=0.5, showscale=False
        )
    )

    fig.update_layout(
        autosize=False,
        width=1000,
        height=1000,
        margin=dict(
            l=5,
            r=5,
            b=10,
            t=10,
            pad=2
        ),    
    )
    
    print(p1)
    print(p2)
    print(p3)
    fig.add_trace(go.Scatter3d(x = [0,x1],
                          y = [0,x2],
                          z = [0,x3],
                          marker = dict(size = [0,5],
                                        color = ['blue'],
                                        line=dict(width=5,
                                        color='DarkSlateGrey')),
                        name = 'b'))
    
    
    fig.add_trace(go.Scatter3d(x = [0,7.5],
                          y = [0,3],
                          z = [0,7.5],
                          marker = dict(size = [0,5],
                                        color = ['blue'],
                                        line=dict(width=10,
                                        color='green')),
                        name = 'p'))
    
    fig.add_trace(go.Scatter3d(x = [3,7.5],
                          y = [3,3],
                          z = [12,7.5],
                          marker = dict(size = [0,5],
                                        color = ['blue'],
                                        line=dict(width=10,
                                        color='green')),
                        name = 'e'))

    fig.show()

In [56]:
plot_projection_onto_surface([3,3, 12], np.matrix([[1, 0, 1], [-1, 1, -1]]).T)

[[-1  0  1]]
[7.5]
[3.]
[7.5]


In [57]:
np.array(np.matrix([6, 0 , 0]))[0][0]

6